FLAGS := -dump-ast-details # -analyse_time_details
TARGET_MAKE_ALL := mine
include ../Common.Makefile


CURRENT := test_debug_function_inline




mine: test_debug_function_inline_out.cpp
	cat test_debug_function_inline_out_enc.cpp


remine: optitrust mine