
FLAGS := -dump-ast-details

#debug: c_ast_debug.out
#debug_enc: c_ast_debug.enc

TESTS := \
	c_address.ml \
	c_stackvar.ml \
	c_features.ml \
	c_ast.ml \
	c_serialize.ml \
	c_compound_assign.ml \
	include_inline.ml \

#	serialize.ml
#   rawc.ml

TARGET_MAKE_ALL := transfo

include ../Common.Makefile
