
# Usage: make optitrust mktasks_out.cpp


TARGET_MAKE_ALL := transfo

OPTITRUST := ../..

TESTS := mktasks.ml

# TRACEFLAGS := -usesingle
# FLAGS_MAKEFILE ?= -report-big-steps -serialized-input none

include ../../tests/Common.Makefile







