open Optitrust
open Prelude

let _ = Flags.check_validity := true
let _ = Flags.recompute_resources_between_steps := true
let _ = Flags.disable_stringreprs := true
let _ = Flags.save_ast_for_steps := Some Flags.Steps_important
let _ = Flags.pretty_matrix_notation := false

let stage_ok = fun i -> i = 1

let _ = Run.script_cpp_stage (stage_ok) (fun () ->
  (* Hoist global memories *)
  !! Matrix.local_name_tile ~uninit_post:true ~var:"a" ~local_var:"d_a" [cFor "x"];
  !! Matrix.local_name_tile ~uninit_pre:true ~var:"b" ~local_var:"d_b" [cFor "x"];
  !! Matrix.memcpy [nbMulti; cFor "i1"];

  (* Create thread hierarchy *)
  let tile (loop_id, tile_size) = Loop.tile (trm_int tile_size)
    ~index:("b" ^ loop_id) ~bound:TileDivides [cFor loop_id] in
  !! List.iter tile [("x", 32); ("y", 32)];
  !! Loop.reorder_at ~order:["by"; "bx"; "y"; "x"] [cArrayWrite "d_b"];

  (* Create shared memory tile *)
  !! Loop.hoist_expr ~dest:[tBefore; cFor "y"] "tile" [cArrayRead "d_a"];
  (* Shared memory allocation happens at the kernel level. We create a
  copy of the tile for each block but use permissions to ensure the tiles
  are never moved between blocks (later). *)
  !! Loop.hoist_alloc ~dest:[tBefore; cFor "by"] [cVarDef "tile"];
  !! Resources.make_strict_loop_contracts [];
)

let _ = Run.script_cpp_stage (stage_ok) (fun () ->
  (* Each thread processes 2 elements of the tile *)
  !! Loop.tile (trm_int 16) ~index:"j" ~bound:TileDivides [ occFirst; cFor "y" ~body:[cFor "x"]];
  (* Reorder write loop so both loops use load coalescing *)
  !! Loop.reorder_at ~order:["x"; "y"] [cArrayWrite "d_b"];
  !! Loop.tile (trm_int 16) ~index:"j" ~bound:TileDivides [ occFirst; cFor "x" ~body:[cFor "y"]];
)

let _ = Run.script_cpp_stage (stage_ok) (fun () ->
  (* Construct terms to pass to kernel_launch *)
  (* LATER: cleaner frontend for building terms *)
  let w,h = (trm_find_var "W" [],trm_find_var "H" []) in
  let tile_size = (trm_int 32) in

  let tpb = [(trm_int 16);tile_size] in
  let bpg = [trm_exact_div_int h tile_size;trm_exact_div_int w tile_size] in
  (* sizeof(float) * 32 * 32 *)
  let smem_szs = [trm_mul_int (trm_sizeof typ_f32) (trm_mul_int tile_size tile_size)] in

  (* Wrap kernel body in launch and kill calls *)
  !! Gpu.create_kernel_launch bpg tpb smem_szs
    ~setup_end:[tBefore; cFor "by"] ~teardown_begin:[tAfter; cFor "by"]
    [occFirst; tBefore; cFor "bx"] [occLast; tAfter; cFor "bx"];

  (* Convert loops to thread for *)
  (* 0 = convert to thread for
     1 = leave as sequential *)
  !! Gpu.convert_tail_thread_for [1;0;1;1] [occLast; cFor "x"; cFor "y"];
  !! Gpu.convert_tail_thread_for [1;0] [occFirst; cFor "y"; cFor "x"];

  (* The transformations above have assumed we don't need to worry about ThreadsCtx,
    only that we have not introduced data races. Now we realize the full construct. *)
  !! Gpu.convert_magic_thread_fors [nbAny; cFor "by"; cFor "" ];

  (* LATER: combination transform to automate most of this (finding nests, converting to real thread for at the end) *)
)

let _ = Run.script_cpp_stage (stage_ok) (fun () ->
  (* Add a mark in the AST to track the main body of the kernel;
    morally similar to Exo cursors *)
  let kernel_mark = "kernel_body" in
  !! Marks.add kernel_mark [occFirst; cFor "by"];

  (* Now that we have established GPU threads, we can convert the memory operations: *)
  !! Gpu.convert_to_global_mem [nbAny; cVarDefs ["d_a";"d_b"]];
  (* Shared memory takes an extra argument *)
  !! Gpu.convert_to_shared_mem ~chop_dims:2 [cVarDef "tile"];

  (* Convert abstract 'magic barriers' to implementable GPU operations *)
  !! Gpu.magic_barrier_to_blocksync [cMark kernel_mark] [cFor "bx"; cCall "magic_barrier"];

  (* A CUDA kernel implicitly synchronizes at the end.
    Move teardown instruction to include the barrier generated by thread for conversion. *)
  !! Instr.move ~dest:[tAfter; cMark kernel_mark] [cCall "kernel_teardown_begin"];
  !! Gpu.magic_barrier_to_teardown_sync [cCall "magic_barrier"];

)

let _ = Run.script_cpp_stage (stage_ok) (fun () ->
  !! Marks.add "kernel_sequence" [cSeq ~instrs_pred:(Target.target_list_one_st [cCall "kernel_launch"]) ()];
  (* TODO: have to disable resource checking temporarily because placement of ghost trips up printer *)
  !! Trace.without_substep_validity_checks (fun () ->
    Trace.without_resource_computation_between_steps (fun () ->
      Instr.move ~dest:[tFirst; cMark "kernel_sequence"] [cCall "kernel_launch"];
      Resources.ensure_computed ();
      Trace.generate_cuda ();
    )
  )
)
