import * as fs from "fs/promises";
import * as path from "path";
import * as vscode from "vscode";
import { fileExists } from "./fileSystem";

export interface AssociatedFile {
  readonly label: string;
  readonly kind: "script" | "input" | "generated" | "expected" | "trace" | "diff" | "other";
  readonly path: string;
}

export interface OutputPair {
  readonly label: string;
  readonly out: string;
  readonly exp: string;
}

export const OPTITRUST_C_SOURCE_EXTENSIONS = [".cpp", ".cc", ".cxx", ".c"] as const;
const OPTITRUST_PRIMARY_INPUT_EXTENSIONS = [...OPTITRUST_C_SOURCE_EXTENSIONS, ".opti"] as const;
const C_SOURCE_EXTENSION_PRIORITY: ReadonlyMap<string, number> = new Map(OPTITRUST_C_SOURCE_EXTENSIONS.map((ext, index) => [ext, index]));
const OUTPUT_EXTENSION_LABELS = new Map<string, string>([
  [".cpp", "C++ output"],
  [".cc", "C++ output"],
  [".cxx", "C++ output"],
  [".c", "C output"],
  [".opti", "OptiLambda output"]
]);
const KIND_ORDER: AssociatedFile["kind"][] = ["script", "input", "generated", "expected", "diff", "trace", "other"];
const OPTILAMBDA_REPRESENTATIONS = ["surface", "internal", "typed"] as const;

type OptilambdaRepresentation = (typeof OPTILAMBDA_REPRESENTATIONS)[number];

const OPTILAMBDA_REPRESENTATION_LABELS: Record<OptilambdaRepresentation, string> = {
  surface: "Surface",
  internal: "Internal",
  typed: "Fully-Typed"
};

export function baseNameForAssociatedFiles(filePath: string): { dir: string; base: string } {
  const parsed = path.parse(filePath);
  const base = normalizeAssociatedBase(parsed.name, parsed.ext);
  return { dir: parsed.dir, base };
}

/**
 * Related OptiTrust artifacts are usually generated by adding a semantic suffix
 * to the script/input base name. Normalizing first lets the same discovery logic
 * work from any related file, for example `foo.ml`, `foo_out.cpp`,
 * `foo_exp.opti`, or `foo_standalone_trace.html`.
 */
function normalizeAssociatedBase(name: string, ext: string): string {
  if (ext === ".trace") {
    return name;
  }
  return stripOptilambdaRepresentationSuffix(name).replace(
    /_(standalone_trace|trace|diff|out|exp|before|after|out_notfmt|exp_notfmt|before_enc|after_enc)$/u,
    ""
  );
}

function optilambdaRepresentationSuffix(name: string): OptilambdaRepresentation | undefined {
  const match = /_(surface|internal|typed)$/u.exec(name);
  return match?.[1] as OptilambdaRepresentation | undefined;
}

function stripOptilambdaRepresentationSuffix(name: string): string {
  const representation = optilambdaRepresentationSuffix(name);
  if (!representation) {
    return name;
  }
  return name.slice(0, -(representation.length + 1));
}

/**
 * Classify by suffix and extension instead of maintaining a fixed candidate
 * list. This keeps associated-file discovery extensible as OptiTrust gains new
 * generated artifacts.
 */
function classifyAssociatedFile(base: string, fileName: string): AssociatedFile["kind"] | undefined {
  const parsed = path.parse(fileName);
  const normalizedBase = normalizeAssociatedBase(parsed.name, parsed.ext);
  if (normalizedBase !== base) {
    return undefined;
  }

  const representation = optilambdaRepresentationSuffix(parsed.name);
  const semanticName = stripOptilambdaRepresentationSuffix(parsed.name);

  if (parsed.ext === ".ml" && parsed.name === base) {
    return "script";
  }
  if (isPrimaryInputExtension(parsed.ext) && parsed.name === base) {
    return "input";
  }
  if (parsed.ext === ".opti" && representation && semanticName === base) {
    return "generated";
  }
  if (/_diff$/u.test(semanticName) && parsed.ext === ".html") {
    return "diff";
  }
  if (
    parsed.ext === ".trace" ||
    (/_trace$/u.test(semanticName) && [".html", ".js"].includes(parsed.ext)) ||
    (/_standalone_trace$/u.test(semanticName) && parsed.ext === ".html")
  ) {
    return "trace";
  }
  if (/_(out|before|after)$/u.test(semanticName) && isPrimaryInputExtension(parsed.ext)) {
    return "generated";
  }
  if (/_exp$/u.test(semanticName) && isPrimaryInputExtension(parsed.ext)) {
    return "expected";
  }
  return "other";
}

function isPrimaryInputExtension(ext: string): boolean {
  return (OPTITRUST_PRIMARY_INPUT_EXTENSIONS as readonly string[]).includes(ext);
}

function isCSourceExtension(ext: string): boolean {
  return (OPTITRUST_C_SOURCE_EXTENSIONS as readonly string[]).includes(ext);
}

function compareAssociatedFiles(a: AssociatedFile, b: AssociatedFile): number {
  const kindOrder = KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind);
  if (kindOrder !== 0) {
    return kindOrder;
  }
  return a.label.localeCompare(b.label);
}

export async function findAssociatedFiles(filePath: string): Promise<AssociatedFile[]> {
  const { dir, base } = baseNameForAssociatedFiles(filePath);
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: AssociatedFile[] = [];

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }
    const kind = classifyAssociatedFile(base, entry.name);
    if (kind) {
      files.push({
        label: entry.name,
        kind,
        path: path.join(dir, entry.name)
      });
    }
  }

  return files.sort(compareAssociatedFiles);
}

export async function findAssociatedCSourceFile(filePath: string): Promise<AssociatedFile | undefined> {
  const files = await findAssociatedFiles(filePath);
  const sources = files.filter(file => file.kind === "input" && isCSourceExtension(path.extname(file.path)));
  return sources.sort(compareCSourcePriority)[0];
}

function compareCSourcePriority(a: AssociatedFile, b: AssociatedFile): number {
  return cSourcePriority(a) - cSourcePriority(b) || a.label.localeCompare(b.label);
}

function cSourcePriority(file: AssociatedFile): number {
  return C_SOURCE_EXTENSION_PRIORITY.get(path.extname(file.path)) ?? Number.MAX_SAFE_INTEGER;
}

/**
 * Detect output/expected pairs generically. VS Code's native diff command can
 * then compare any supported output language without command-specific code.
 */
export async function outputPairs(filePath: string): Promise<OutputPair[]> {
  const { dir, base } = baseNameForAssociatedFiles(filePath);
  const pairs: OutputPair[] = [];
  for (const [ext, label] of OUTPUT_EXTENSION_LABELS) {
    const pair = {
      label,
      out: path.join(dir, `${base}_out${ext}`),
      exp: path.join(dir, `${base}_exp${ext}`)
    };
    if ((await fileExists(pair.out)) && (await fileExists(pair.exp))) {
      pairs.push(pair);
    }
  }

  for (const representation of OPTILAMBDA_REPRESENTATIONS) {
    const pair = {
      label: `OptiLambda ${OPTILAMBDA_REPRESENTATION_LABELS[representation]} output`,
      out: path.join(dir, `${base}_out_${representation}.opti`),
      exp: path.join(dir, `${base}_exp_${representation}.opti`)
    };
    if ((await fileExists(pair.out)) && (await fileExists(pair.exp))) {
      pairs.push(pair);
    }
  }

  return pairs;
}

export async function pickAssociatedFile(files: AssociatedFile[], placeHolder: string): Promise<AssociatedFile | undefined> {
  if (files.length === 0) {
    return undefined;
  }
  if (files.length === 1) {
    return files[0];
  }

  return vscode.window.showQuickPick(
    files.map(file => ({
      label: file.label,
      description: file.kind,
      detail: file.path,
      file
    })),
    { placeHolder }
  ).then(item => item?.file);
}
