import * as fs from "fs/promises";
import * as path from "path";
import * as vscode from "vscode";

export interface AssociatedFile {
  readonly label: string;
  readonly kind: "script" | "input" | "generated" | "expected" | "trace" | "diff" | "other";
  readonly path: string;
}

export interface OutputPair {
  readonly label: string;
  readonly out: string;
  readonly exp: string;
}

const KIND_ORDER: AssociatedFile["kind"][] = ["script", "input", "generated", "expected", "diff", "trace", "other"];

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

export function baseNameForAssociatedFiles(filePath: string): { dir: string; base: string } {
  const parsed = path.parse(filePath);
  const base = normalizeAssociatedBase(parsed.name, parsed.ext);
  return { dir: parsed.dir, base };
}

/**
 * Related OptiTrust artifacts are usually generated by adding a semantic suffix
 * to the script/input base name. Normalizing first lets the same discovery logic
 * work from any related file, for example `foo.ml`, `foo_out.cpp`,
 * `foo_exp.opti`, or `foo_standalone_trace.html`.
 */
function normalizeAssociatedBase(name: string, ext: string): string {
  if (ext === ".trace") {
    return name;
  }
  return name.replace(
    /_(standalone_trace|trace|diff|out|exp|before|after|out_notfmt|exp_notfmt|before_enc|after_enc)$/u,
    ""
  );
}

/**
 * Classify by suffix and extension instead of maintaining a fixed candidate
 * list. This keeps associated-file discovery extensible as OptiTrust gains new
 * generated artifacts.
 */
function classifyAssociatedFile(base: string, fileName: string): AssociatedFile["kind"] | undefined {
  const parsed = path.parse(fileName);
  const normalizedBase = normalizeAssociatedBase(parsed.name, parsed.ext);
  if (normalizedBase !== base) {
    return undefined;
  }

  if (parsed.ext === ".ml" && parsed.name === base) {
    return "script";
  }
  if ([".cpp", ".c", ".opti"].includes(parsed.ext) && parsed.name === base) {
    return "input";
  }
  if (/_diff$/u.test(parsed.name) && parsed.ext === ".html") {
    return "diff";
  }
  if (
    parsed.ext === ".trace" ||
    (/_trace$/u.test(parsed.name) && [".html", ".js"].includes(parsed.ext)) ||
    (/_standalone_trace$/u.test(parsed.name) && parsed.ext === ".html")
  ) {
    return "trace";
  }
  if (/_(out|before|after)$/u.test(parsed.name) && [".cpp", ".c", ".opti"].includes(parsed.ext)) {
    return "generated";
  }
  if (/_exp$/u.test(parsed.name) && [".cpp", ".c", ".opti"].includes(parsed.ext)) {
    return "expected";
  }
  return "other";
}

function compareAssociatedFiles(a: AssociatedFile, b: AssociatedFile): number {
  const kindOrder = KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind);
  if (kindOrder !== 0) {
    return kindOrder;
  }
  return a.label.localeCompare(b.label);
}

export async function findAssociatedFiles(filePath: string): Promise<AssociatedFile[]> {
  const { dir, base } = baseNameForAssociatedFiles(filePath);
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: AssociatedFile[] = [];

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }
    const kind = classifyAssociatedFile(base, entry.name);
    if (kind) {
      files.push({
        label: entry.name,
        kind,
        path: path.join(dir, entry.name)
      });
    }
  }

  return files.sort(compareAssociatedFiles);
}

/**
 * Detect output/expected pairs generically. VS Code's native diff command can
 * then compare any supported output language without command-specific code.
 */
export async function outputPairs(filePath: string): Promise<OutputPair[]> {
  const { dir, base } = baseNameForAssociatedFiles(filePath);
  const pairs: OutputPair[] = [];
  const labels = new Map([
    [".cpp", "C/C++ output"],
    [".c", "C output"],
    [".opti", "OptiLambda output"]
  ]);

  for (const ext of [".cpp", ".c", ".opti"]) {
    const pair = {
      label: labels.get(ext) ?? `${ext.slice(1).toUpperCase()} output`,
      out: path.join(dir, `${base}_out${ext}`),
      exp: path.join(dir, `${base}_exp${ext}`)
    };
    if ((await exists(pair.out)) && (await exists(pair.exp))) {
      pairs.push(pair);
    }
  }
  return pairs;
}

export async function pickAssociatedFile(files: AssociatedFile[], placeHolder: string): Promise<AssociatedFile | undefined> {
  if (files.length === 0) {
    return undefined;
  }
  if (files.length === 1) {
    return files[0];
  }

  return vscode.window.showQuickPick(
    files.map(file => ({
      label: file.label,
      description: file.kind,
      detail: file.path,
      file
    })),
    { placeHolder }
  ).then(item => item?.file);
}
