import * as fs from "fs/promises";
import * as path from "path";
import * as vscode from "vscode";

const panels = new Map<string, vscode.WebviewPanel>();

function webviewKey(filePath: string, viewKind: string, metadata: string): string {
  return `${path.resolve(filePath)}::${viewKind}::${metadata}`;
}

/**
 * OptiTrust diff/trace pages are generated as normal browser pages. VS Code
 * webviews run with a stricter resource model, so local assets must be inlined
 * or rewritten before the HTML can be displayed reliably inside the editor.
 */
async function htmlWithBase(webview: vscode.Webview, htmlFile: string): Promise<string> {
  const html = await fs.readFile(htmlFile, "utf8");
  const htmlDir = path.dirname(htmlFile);
  const inlined = await inlineLocalScriptsAndStyles(htmlDir, html);
  const rewritten = rewriteLocalResourceUris(webview, htmlDir, inlined);
  return injectDiffFallback(injectDiffWebviewStyle(rewritten));
}

/**
 * Inline local JS/CSS dependencies generated by OptiTrust. This keeps the
 * existing HTML templates usable both in a browser and in VS Code webviews,
 * where relative script loading can otherwise fail depending on the generated
 * file location.
 */
async function inlineLocalScriptsAndStyles(htmlDir: string, html: string): Promise<string> {
  const withScripts = await replaceMatches(html, /<script([^>]*)\bsrc="([^"]+)"([^>]*)><\/script>/giu, async match => {
    const [, beforeSrc, value, afterSrc] = match;
    if (!isLocalPath(value) || path.extname(value.split(/[?#]/u, 1)[0]) !== ".js") {
      return match[0];
    }

    const scriptPath = path.resolve(htmlDir, value.split(/[?#]/u, 1)[0]);
    const script = await fs.readFile(scriptPath, "utf8");
    return `<script${beforeSrc}${afterSrc}>\n${script}\n</script>`;
  });

  return replaceMatches(withScripts, /<link([^>]*)\bhref="([^"]+)"([^>]*)>/giu, async match => {
    const [, beforeHref, value, afterHref] = match;
    const attributes = `${beforeHref}${afterHref}`;
    if (!isLocalPath(value) || !/\brel="stylesheet"/iu.test(attributes) || path.extname(value.split(/[?#]/u, 1)[0]) !== ".css") {
      return match[0];
    }

    const stylePath = path.resolve(htmlDir, value.split(/[?#]/u, 1)[0]);
    const style = await fs.readFile(stylePath, "utf8");
    return `<style>\n${style}\n</style>`;
  });
}

/**
 * Preserve external/data/hash URLs, but rewrite local resource paths through
 * VS Code's webview URI API. This is required for images or other local assets
 * that remain referenced after the inline pass.
 */
function rewriteLocalResourceUris(webview: vscode.Webview, htmlDir: string, html: string): string {
  return html.replace(/\b(src|href)="([^"]+)"/gu, (_match, attr: string, value: string) => {
    if (!isLocalPath(value)) {
      return `${attr}="${value}"`;
    }

    const [resourcePath, suffix = ""] = value.split(/(?=[?#])/u, 2);
    const resourceUri = webview.asWebviewUri(vscode.Uri.file(path.resolve(htmlDir, resourcePath)));
    return `${attr}="${resourceUri}${suffix}"`;
  });
}

function isLocalPath(value: string): boolean {
  return !/^(?:https?:|data:|#|vscode-resource:|vscode-webview-resource:|vscode-webview:)/iu.test(value);
}

async function replaceMatches(
  text: string,
  pattern: RegExp,
  replaceMatch: (match: RegExpMatchArray) => Promise<string>
): Promise<string> {
  let result = "";
  let offset = 0;
  for (const match of text.matchAll(pattern)) {
    if (match.index === undefined) {
      continue;
    }
    result += text.slice(offset, match.index);
    result += await replaceMatch(match);
    offset = match.index + match[0].length;
  }
  return result + text.slice(offset);
}

function injectDiffWebviewStyle(html: string): string {
  if (!html.includes('id="diffDiv"')) {
    return html;
  }

  const style = `
<style>
html,
body,
#diffDiv,
.d2h-wrapper,
.d2h-file-wrapper,
.d2h-file-diff,
.d2h-files-diff,
.d2h-file-side-diff,
.d2h-code-wrapper,
.d2h-diff-table {
  background: var(--vscode-editor-background, #fff);
}
</style>`;

  if (html.includes("</head>")) {
    return html.replace("</head>", `${style}\n</head>`);
  }
  return `${style}\n${html}`;
}

/**
 * The diff renderer occasionally fails to initialize under webview security or
 * asset-loading constraints. Showing the raw diff is preferable to an empty
 * panel because the OptiTrust command itself has already succeeded.
 */
function injectDiffFallback(html: string): string {
  if (!html.includes('id="diffDiv"')) {
    return html;
  }

  const fallbackScript = `
<script>
function renderOptitrustRawDiffFallback() {
  var target = document.getElementById('diffDiv');
  if (!target || target.textContent.trim() !== '' || typeof diffString !== 'string') {
    return;
  }
  var warning = document.createElement('p');
  warning.textContent = 'OptiTrust rendered the raw diff because the interactive diff viewer did not load inside VS Code.';
  warning.style.fontFamily = 'sans-serif';
  warning.style.color = '#a15c00';
  var pre = document.createElement('pre');
  pre.textContent = diffString;
  pre.style.whiteSpace = 'pre-wrap';
  pre.style.fontFamily = 'var(--vscode-editor-font-family, monospace)';
  pre.style.fontSize = 'var(--vscode-editor-font-size, 13px)';
  pre.style.background = 'var(--vscode-editor-background, #fff)';
  pre.style.color = 'var(--vscode-editor-foreground, #24292f)';
  pre.style.padding = '12px';
  pre.style.overflow = 'auto';
  target.appendChild(warning);
  target.appendChild(pre);
}

window.addEventListener('error', function () {
  window.setTimeout(renderOptitrustRawDiffFallback, 0);
});
document.addEventListener('DOMContentLoaded', function () {
  window.setTimeout(function () {
    renderOptitrustRawDiffFallback();
  }, 800);
});
</script>`;

  if (html.includes("</body>")) {
    return html.replace("</body>", `${fallbackScript}\n</body>`);
  }
  return `${html}\n${fallbackScript}`;
}

export async function openHtmlView(root: string, htmlFile: string, viewKind: string, metadata: string, title: string): Promise<void> {
  const key = webviewKey(htmlFile, viewKind, metadata);
  const existing = panels.get(key);
  if (existing) {
    existing.reveal(vscode.ViewColumn.Beside);
    existing.webview.html = await htmlWithBase(existing.webview, htmlFile);
    return;
  }

  const panel = vscode.window.createWebviewPanel("optitrustView", title, vscode.ViewColumn.Beside, {
    enableScripts: true,
    localResourceRoots: [vscode.Uri.file(root), vscode.Uri.file(path.dirname(htmlFile))]
  });

  panel.onDidDispose(() => panels.delete(key));
  panel.webview.html = await htmlWithBase(panel.webview, htmlFile);
  panels.set(key, panel);
}

export async function openFileOrHtml(root: string, filePath: string, title?: string): Promise<void> {
  if (path.extname(filePath) === ".html") {
    await openHtmlView(root, filePath, "associated", path.basename(filePath), title ?? path.basename(filePath));
    return;
  }

  const document = await vscode.workspace.openTextDocument(vscode.Uri.file(filePath));
  await vscode.window.showTextDocument(document, vscode.ViewColumn.Beside);
}
