import * as fs from "fs/promises";
import * as path from "path";
import * as vscode from "vscode";

const panels = new Map<string, vscode.WebviewPanel>();
const MAX_INLINE_ASSET_BYTES = 2 * 1024 * 1024;

function webviewKey(filePath: string, viewKind: string, metadata: string): string {
  return `${path.resolve(filePath)}::${viewKind}::${metadata}`;
}

/**
 * OptiTrust diff/trace pages are generated as normal browser pages. VS Code
 * webviews run with a stricter resource model, so local assets must be inlined
 * or rewritten before the HTML can be displayed reliably inside the editor.
 */
async function htmlWithBase(webview: vscode.Webview, htmlFile: string): Promise<string> {
  const html = await fs.readFile(htmlFile, "utf8");
  const htmlDir = path.dirname(htmlFile);
  const inlined = await inlineLocalScriptsAndStyles(htmlDir, html);
  const rewritten = rewriteLocalResourceUris(webview, htmlDir, inlined);
  const withHighlightingConfig = await injectSyntaxHighlightingConfig(rewritten);
  return injectDiffFallback(injectDiffWebviewStyle(withHighlightingConfig));
}

/**
 * Inline local JS/CSS dependencies generated by OptiTrust. This keeps the
 * existing HTML templates usable both in a browser and in VS Code webviews,
 * where relative script loading can otherwise fail depending on the generated
 * file location.
 */
async function inlineLocalScriptsAndStyles(htmlDir: string, html: string): Promise<string> {
  const withScripts = await replaceMatches(html, /<script([^>]*)\bsrc="([^"]+)"([^>]*)><\/script>/giu, async match => {
    const [, beforeSrc, value, afterSrc] = match;
    const attributes = `${beforeSrc}${afterSrc}`;
    if (/\btype\s*=\s*["']module["']/iu.test(attributes)) {
      return match[0];
    }
    if (!isLocalPath(value) || path.extname(value.split(/[?#]/u, 1)[0]) !== ".js") {
      return match[0];
    }

    const scriptPath = path.resolve(htmlDir, value.split(/[?#]/u, 1)[0]);
    if (await shouldKeepExternal(scriptPath)) {
      return match[0];
    }
    const script = await fs.readFile(scriptPath, "utf8");
    return `<script${beforeSrc}${afterSrc}>\n${script}\n</script>`;
  });

  return replaceMatches(withScripts, /<link([^>]*)\bhref="([^"]+)"([^>]*)>/giu, async match => {
    const [, beforeHref, value, afterHref] = match;
    const attributes = `${beforeHref}${afterHref}`;
    if (!isLocalPath(value) || !/\brel="stylesheet"/iu.test(attributes) || path.extname(value.split(/[?#]/u, 1)[0]) !== ".css") {
      return match[0];
    }

    const stylePath = path.resolve(htmlDir, value.split(/[?#]/u, 1)[0]);
    if (await shouldKeepExternal(stylePath)) {
      return match[0];
    }
    const style = await fs.readFile(stylePath, "utf8");
    return `<style>\n${style}\n</style>`;
  });
}

async function shouldKeepExternal(filePath: string): Promise<boolean> {
  const stat = await fs.stat(filePath);
  return stat.size > MAX_INLINE_ASSET_BYTES;
}

/**
 * Preserve external/data/hash URLs, but rewrite local resource paths through
 * VS Code's webview URI API. This is required for images or other local assets
 * that remain referenced after the inline pass.
 */
function rewriteLocalResourceUris(webview: vscode.Webview, htmlDir: string, html: string): string {
  return html.replace(/\b(src|href)="([^"]+)"/gu, (_match, attr: string, value: string) => {
    if (!isLocalPath(value)) {
      return `${attr}="${value}"`;
    }

    const [resourcePath, suffix = ""] = value.split(/(?=[?#])/u, 2);
    const resourceUri = webview.asWebviewUri(vscode.Uri.file(path.resolve(htmlDir, resourcePath)));
    return `${attr}="${resourceUri}${suffix}"`;
  });
}

function isLocalPath(value: string): boolean {
  return !/^(?:https?:|data:|#|vscode-resource:|vscode-webview-resource:|vscode-webview:)/iu.test(value);
}

async function replaceMatches(
  text: string,
  pattern: RegExp,
  replaceMatch: (match: RegExpMatchArray) => Promise<string>
): Promise<string> {
  let result = "";
  let offset = 0;
  for (const match of text.matchAll(pattern)) {
    if (match.index === undefined) {
      continue;
    }
    result += text.slice(offset, match.index);
    result += await replaceMatch(match);
    offset = match.index + match[0].length;
  }
  return result + text.slice(offset);
}

function injectDiffWebviewStyle(html: string): string {
  if (!html.includes('id="diffDiv"')) {
    return html;
  }

  const style = `
<style>
html,
body,
#diffDiv,
.d2h-wrapper,
.d2h-file-wrapper,
.d2h-file-diff,
.d2h-files-diff,
.d2h-file-side-diff,
.d2h-code-wrapper,
.d2h-diff-table {
  background: var(--vscode-editor-background, #fff);
}
</style>`;

  if (html.includes("</head>")) {
    return html.replace("</head>", `${style}\n</head>`);
  }
  return `${style}\n${html}`;
}

interface TextMateRule {
  readonly scope?: string | readonly string[];
  readonly settings?: Record<string, unknown>;
}

interface ThemeJson {
  readonly name?: string;
  readonly type?: string;
  readonly include?: string;
  readonly colors?: Record<string, string>;
  readonly tokenColors?: readonly TextMateRule[];
  readonly settings?: readonly TextMateRule[];
  readonly semanticHighlighting?: boolean;
  readonly semanticTokenColors?: Record<string, unknown>;
}

interface WebviewHighlightConfig {
  readonly theme?: ThemeJson;
}

async function injectSyntaxHighlightingConfig(html: string): Promise<string> {
  if (!html.includes('id="diffDiv"') || html.includes('id="optitrustSyntaxHighlightConfig"')) {
    return html;
  }

  const config: WebviewHighlightConfig = {
    theme: await activeThemeJson()
  };
  const script = `<script type="application/json" id="optitrustSyntaxHighlightConfig">${escapeScriptJson(JSON.stringify(config))}</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}\n</head>`);
  }
  return `${script}\n${html}`;
}

async function activeThemeJson(): Promise<ThemeJson | undefined> {
  const activeTheme = vscode.workspace.getConfiguration("workbench").get<string>("colorTheme", "");
  const themePath = activeTheme ? findThemePath(activeTheme) : undefined;
  if (!themePath) {
    return undefined;
  }

  try {
    const theme = await loadThemeJson(themePath);
    const customRules = customTokenRules(activeTheme);
    const tokenColors = [...themeRules(theme), ...customRules];
    return {
      ...theme,
      name: "optitrust-active-vscode-theme",
      tokenColors
    };
  } catch (error) {
    console.warn(`OptiTrust: failed to load VS Code theme ${activeTheme}: ${error instanceof Error ? error.message : String(error)}`);
    return undefined;
  }
}

function findThemePath(activeTheme: string): string | undefined {
  for (const extension of vscode.extensions.all) {
    const themes = extension.packageJSON?.contributes?.themes;
    if (!Array.isArray(themes)) {
      continue;
    }
    for (const theme of themes) {
      if ((theme.id === activeTheme || theme.label === activeTheme) && typeof theme.path === "string") {
        return path.join(extension.extensionPath, theme.path);
      }
    }
  }
  return undefined;
}

async function loadThemeJson(themePath: string, seen: Set<string> = new Set()): Promise<ThemeJson> {
  const resolved = path.resolve(themePath);
  if (seen.has(resolved)) {
    return {};
  }
  seen.add(resolved);

  const theme = parseJsonWithComments<ThemeJson>(await fs.readFile(resolved, "utf8"));
  const inherited = theme.include ? await loadThemeJson(path.resolve(path.dirname(resolved), theme.include), seen) : {};
  return {
    ...inherited,
    ...theme,
    colors: {
      ...(inherited.colors ?? {}),
      ...(theme.colors ?? {})
    },
    tokenColors: [
      ...themeRules(inherited),
      ...themeRules(theme)
    ]
  };
}

function customTokenRules(activeTheme: string): TextMateRule[] {
  const customizations = vscode.workspace.getConfiguration("editor").get<Record<string, unknown>>("tokenColorCustomizations", {});
  const rules: TextMateRule[] = [];
  rules.push(...textMateRulesFrom(customizations.textMateRules));

  const themeSpecific = customizations[`[${activeTheme}]`];
  if (isRecord(themeSpecific)) {
    rules.push(...textMateRulesFrom(themeSpecific.textMateRules));
  }
  return rules;
}

function themeRules(theme: ThemeJson): TextMateRule[] {
  return [
    ...textMateRulesFrom(theme.settings),
    ...textMateRulesFrom(theme.tokenColors)
  ];
}

function textMateRulesFrom(value: unknown): TextMateRule[] {
  return Array.isArray(value) ? value.filter(isTextMateRule) : [];
}

function isTextMateRule(value: unknown): value is TextMateRule {
  return isRecord(value) && isRecord(value.settings);
}

function parseJsonWithComments<T>(text: string): T {
  return JSON.parse(stripJsonComments(text)) as T;
}

function stripJsonComments(text: string): string {
  return text
    .replace(/\/\*[\s\S]*?\*\//gu, "")
    .replace(/(^|[^:])\/\/.*$/gmu, "$1");
}

function escapeScriptJson(value: string): string {
  return value.replace(/[<\u2028\u2029]/gu, character => {
    if (character === "<") {
      return "\\u003c";
    }
    if (character === "\u2028") {
      return "\\u2028";
    }
    return "\\u2029";
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/**
 * The diff renderer occasionally fails to initialize under webview security or
 * asset-loading constraints. Showing the raw diff is preferable to an empty
 * panel because the OptiTrust command itself has already succeeded.
 */
function injectDiffFallback(html: string): string {
  if (!html.includes('id="diffDiv"')) {
    return html;
  }

  const fallbackScript = `
<script>
function getOptitrustRawDiffString() {
  if (typeof diffString === 'string') {
    return diffString;
  }
  if (typeof diffStrings === 'object' && diffStrings !== null) {
    var selected = typeof selectedDiffRepresentation === 'string' ? selectedDiffRepresentation : 'cpp';
    return diffStrings[selected] || diffStrings.cpp || diffStrings.surface || diffStrings.internal || diffStrings.typed || '';
  }
  return '';
}

function renderOptitrustRawDiffFallback() {
  var target = document.getElementById('diffDiv');
  var rawDiff = getOptitrustRawDiffString();
  if (!target || target.textContent.trim() !== '' || rawDiff === '') {
    return;
  }
  var warning = document.createElement('p');
  warning.textContent = 'OptiTrust rendered the raw diff because the interactive diff viewer did not load inside VS Code.';
  warning.style.fontFamily = 'sans-serif';
  warning.style.color = '#a15c00';
  var pre = document.createElement('pre');
  pre.textContent = rawDiff;
  pre.style.whiteSpace = 'pre-wrap';
  pre.style.fontFamily = 'var(--vscode-editor-font-family, monospace)';
  pre.style.fontSize = 'var(--vscode-editor-font-size, 13px)';
  pre.style.background = 'var(--vscode-editor-background, #fff)';
  pre.style.color = 'var(--vscode-editor-foreground, #24292f)';
  pre.style.padding = '12px';
  pre.style.overflow = 'auto';
  target.appendChild(warning);
  target.appendChild(pre);
}

window.addEventListener('error', function () {
  window.setTimeout(renderOptitrustRawDiffFallback, 0);
});
document.addEventListener('DOMContentLoaded', function () {
  window.setTimeout(function () {
    renderOptitrustRawDiffFallback();
  }, 800);
});
</script>`;

  if (html.includes("</body>")) {
    return html.replace("</body>", `${fallbackScript}\n</body>`);
  }
  return `${html}\n${fallbackScript}`;
}

export async function openHtmlView(root: string, htmlFile: string, viewKind: string, metadata: string, title: string): Promise<void> {
  const key = webviewKey(htmlFile, viewKind, metadata);
  const existing = panels.get(key);
  if (existing) {
    existing.webview.html = await htmlWithBase(existing.webview, htmlFile);
    // Reopening an existing view should refresh it in place. Passing
    // ViewColumn.Beside here moves the tab back next to the active editor,
    // which is disruptive when users place diff/trace panels on another group
    // or screen.
    existing.reveal(existing.viewColumn, true);
    return;
  }

  const panel = vscode.window.createWebviewPanel("optitrustView", title, vscode.ViewColumn.Beside, {
    enableScripts: true,
    localResourceRoots: [vscode.Uri.file(root), vscode.Uri.file(path.dirname(htmlFile))]
  });

  panel.onDidDispose(() => panels.delete(key));
  panel.webview.html = await htmlWithBase(panel.webview, htmlFile);
  panels.set(key, panel);
}

export async function openFileOrHtml(root: string, filePath: string, title?: string): Promise<void> {
  if (path.extname(filePath) === ".html") {
    await openHtmlView(root, filePath, "associated", path.basename(filePath), title ?? path.basename(filePath));
    return;
  }

  const document = await vscode.workspace.openTextDocument(vscode.Uri.file(filePath));
  await vscode.window.showTextDocument(document, vscode.ViewColumn.Beside);
}
