import * as fs from "fs/promises";
import * as path from "path";
import * as vscode from "vscode";
import {
  attachLiveView,
  clearLiveView,
  detachLiveView,
  isAttachedLiveView,
  prepareAttachedLiveView,
  setActiveLiveViewContext
} from "./liveView";
import { appendLine } from "./output";
import { runCommand } from "./runner";
import { backendFlagsForViewMode, VIEW_MODES } from "./viewMode";

const panels = new Map<string, vscode.WebviewPanel>();
const panelStates = new Map<string, PanelRuntimeState>();
const MAX_INLINE_ASSET_BYTES = 2 * 1024 * 1024;
const LIVE_VIEW_KEY = "optitrust-live-view";
export const OPTITRUST_WEBVIEW_TYPE = "optitrustView";

interface OpenHtmlViewOptions {
  readonly useLiveView?: boolean;
  readonly lazyDiff?: LazyDiffContext;
  readonly initialDiffRepresentation?: string;
}

interface HtmlTransformOptions {
  readonly includeDetachButton?: boolean;
  readonly initialDiffRepresentation?: string;
  readonly detached?: boolean;
}

interface LazyDiffContext {
  readonly relativePath: string;
  readonly line: number;
}

interface PanelRuntimeState {
  root: string;
  htmlFile: string;
  includeDetachButton?: boolean;
  lazyDiff?: LazyDiffContext;
  initialDiffRepresentation?: string;
  detached?: boolean;
}

function webviewKey(filePath: string, viewKind: string, metadata: string): string {
  return `${path.resolve(filePath)}::${viewKind}::${metadata}`;
}

/**
 * OptiTrust diff/trace pages are generated as normal browser pages. VS Code
 * webviews run with a stricter resource model, so local assets must be inlined
 * or rewritten before the HTML can be displayed reliably inside the editor.
 */
async function htmlWithBase(webview: vscode.Webview, root: string, htmlFile: string, options: HtmlTransformOptions = {}): Promise<string> {
  const html = await fs.readFile(htmlFile, "utf8");
  const htmlDir = path.dirname(htmlFile);
  const inlined = await inlineLocalScriptsAndStyles(htmlDir, html);
  const rewritten = rewriteLocalResourceUris(webview, htmlDir, inlined);
  const withTraceServerBase = injectTraceServerBase(root, htmlFile, rewritten);
  const withHighlightingConfig = await injectSyntaxHighlightingConfig(withTraceServerBase);
  const withDiffSupport = injectDiffInitialRepresentation(
    injectDiffFallback(injectDiffWebviewStyle(withHighlightingConfig)),
    options.initialDiffRepresentation
  );
  return options.includeDetachButton ? injectDetachButton(withDiffSupport, options.detached ?? false) : withDiffSupport;
}

function injectDiffInitialRepresentation(html: string, representation?: string): string {
  if (!representation || !html.includes("diffStrings")) {
    return html;
  }
  const script = `<script>window.optitrustInitialDiffRepresentation = ${JSON.stringify(representation)};</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}\n</head>`);
  }
  return `${script}\n${html}`;
}

function injectTraceServerBase(root: string, htmlFile: string, html: string): string {
  if (!html.includes("serialized_trace") || html.includes('id="optitrustTraceServerBaseUrl"')) {
    return html;
  }

  const relativeDir = path.dirname(path.relative(root, htmlFile));
  const urlPath = relativeDir === "." ? "" : `${relativeDir.split(path.sep).map(encodeURIComponent).join("/")}/`;
  const baseUrl = `http://localhost:6775/${urlPath}`;
  const script = `<script id="optitrustTraceServerBaseUrl">window.optitrustTraceServerBaseUrl = ${JSON.stringify(baseUrl)};</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}\n</head>`);
  }
  return `${script}\n${html}`;
}

/**
 * Inline local JS/CSS dependencies generated by OptiTrust. This keeps the
 * existing HTML templates usable both in a browser and in VS Code webviews,
 * where relative script loading can otherwise fail depending on the generated
 * file location.
 */
async function inlineLocalScriptsAndStyles(htmlDir: string, html: string): Promise<string> {
  const withScripts = await replaceMatches(html, /<script([^>]*)\bsrc="([^"]+)"([^>]*)><\/script>/giu, async match => {
    const [, beforeSrc, value, afterSrc] = match;
    const attributes = `${beforeSrc}${afterSrc}`;
    if (/\btype\s*=\s*["']module["']/iu.test(attributes)) {
      return match[0];
    }
    if (!isLocalPath(value) || path.extname(value.split(/[?#]/u, 1)[0]) !== ".js") {
      return match[0];
    }

    const scriptPath = path.resolve(htmlDir, value.split(/[?#]/u, 1)[0]);
    if (await shouldKeepExternal(scriptPath)) {
      return match[0];
    }
    const script = await fs.readFile(scriptPath, "utf8");
    return `<script${beforeSrc}${afterSrc}>\n${script}\n</script>`;
  });

  return replaceMatches(withScripts, /<link([^>]*)\bhref="([^"]+)"([^>]*)>/giu, async match => {
    const [, beforeHref, value, afterHref] = match;
    const attributes = `${beforeHref}${afterHref}`;
    if (!isLocalPath(value) || !/\brel="stylesheet"/iu.test(attributes) || path.extname(value.split(/[?#]/u, 1)[0]) !== ".css") {
      return match[0];
    }

    const stylePath = path.resolve(htmlDir, value.split(/[?#]/u, 1)[0]);
    if (await shouldKeepExternal(stylePath)) {
      return match[0];
    }
    const style = await fs.readFile(stylePath, "utf8");
    return `<style>\n${style}\n</style>`;
  });
}

async function shouldKeepExternal(filePath: string): Promise<boolean> {
  const stat = await fs.stat(filePath);
  return stat.size > MAX_INLINE_ASSET_BYTES;
}

/**
 * Preserve external/data/hash URLs, but rewrite local resource paths through
 * VS Code's webview URI API. This is required for images or other local assets
 * that remain referenced after the inline pass.
 */
function rewriteLocalResourceUris(webview: vscode.Webview, htmlDir: string, html: string): string {
  return html.replace(/\b(src|href)="([^"]+)"/gu, (_match, attr: string, value: string) => {
    if (!isLocalPath(value)) {
      return `${attr}="${value}"`;
    }

    const [resourcePath, suffix = ""] = value.split(/(?=[?#])/u, 2);
    const resourceUri = webview.asWebviewUri(vscode.Uri.file(path.resolve(htmlDir, resourcePath)));
    return `${attr}="${resourceUri}${suffix}"`;
  });
}

function isLocalPath(value: string): boolean {
  return !/^(?:https?:|data:|#|vscode-resource:|vscode-webview-resource:|vscode-webview:)/iu.test(value);
}

async function replaceMatches(
  text: string,
  pattern: RegExp,
  replaceMatch: (match: RegExpMatchArray) => Promise<string>
): Promise<string> {
  let result = "";
  let offset = 0;
  for (const match of text.matchAll(pattern)) {
    if (match.index === undefined) {
      continue;
    }
    result += text.slice(offset, match.index);
    result += await replaceMatch(match);
    offset = match.index + match[0].length;
  }
  return result + text.slice(offset);
}

function injectDiffWebviewStyle(html: string): string {
  if (!html.includes('id="diffDiv"')) {
    return html;
  }

  const style = `
<style>
html,
body,
#diffDiv,
.d2h-wrapper,
.d2h-file-wrapper,
.d2h-file-diff,
.d2h-files-diff,
.d2h-file-side-diff,
.d2h-code-wrapper,
.d2h-diff-table {
  background: var(--vscode-editor-background, #fff);
}
</style>`;

  if (html.includes("</head>")) {
    return html.replace("</head>", `${style}\n</head>`);
  }
  return `${style}\n${html}`;
}

interface TextMateRule {
  readonly scope?: string | readonly string[];
  readonly settings?: Record<string, unknown>;
}

interface ThemeJson {
  readonly name?: string;
  readonly type?: string;
  readonly include?: string;
  readonly colors?: Record<string, string>;
  readonly tokenColors?: readonly TextMateRule[];
  readonly settings?: readonly TextMateRule[];
  readonly semanticHighlighting?: boolean;
  readonly semanticTokenColors?: Record<string, unknown>;
}

interface WebviewHighlightConfig {
  readonly theme?: ThemeJson;
  readonly builtinTheme?: "dark-plus" | "light-plus";
  readonly requestedTheme?: string;
  readonly themePath?: string;
  readonly themeExtension?: string;
  readonly themeLabel?: string;
  readonly themeRuleCount?: number;
  readonly customRuleCount?: number;
  readonly resolutionStatus: "configured-theme" | "vscode-theme" | "shiki-builtin" | "fallback";
}

async function injectSyntaxHighlightingConfig(html: string): Promise<string> {
  if (!html.includes('id="diffDiv"') || html.includes('id="optitrustSyntaxHighlightConfig"')) {
    return html;
  }

  const config = await activeHighlightConfig();
  const script = `<script type="application/json" id="optitrustSyntaxHighlightConfig">${escapeScriptJson(JSON.stringify(config))}</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}\n</head>`);
  }
  return `${script}\n${html}`;
}

async function activeHighlightConfig(): Promise<WebviewHighlightConfig> {
  const activeTheme = vscode.workspace.getConfiguration("workbench").get<string>("colorTheme", "");
  const customRules = customTokenRules(activeTheme);
  const configuredThemePath = syntaxHighlightThemePath();
  if (configuredThemePath) {
    const theme = await activeThemeJson(activeTheme, configuredThemePath, customRules);
    if (theme) {
      return {
        requestedTheme: activeTheme,
        themePath: configuredThemePath,
        themeLabel: path.basename(configuredThemePath),
        customRuleCount: customRules.length,
        theme,
        themeRuleCount: themeRules(theme).length,
        resolutionStatus: "configured-theme"
      };
    }
    appendLine(`OptiTrust syntax highlight: configured theme path "${configuredThemePath}" could not be loaded; continuing with automatic theme resolution.`);
  }

  const resolved = activeTheme ? findTheme(activeTheme) : undefined;
  const configBase = {
    requestedTheme: activeTheme,
    themePath: resolved?.path,
    themeExtension: resolved?.extensionId,
    themeLabel: resolved?.label,
    customRuleCount: customRules.length
  };
  if (!resolved) {
    const builtinTheme = builtinShikiTheme(activeTheme);
    if (builtinTheme) {
      return {
        ...configBase,
        builtinTheme,
        resolutionStatus: "shiki-builtin"
      };
    }
    appendLine(`OptiTrust syntax highlight: VS Code theme "${activeTheme || "(empty)"}" was not found; webviews will use Shiki fallback colors.`);
    return {
      ...configBase,
      resolutionStatus: "fallback"
    };
  }
  const theme = await activeThemeJson(activeTheme, resolved.path, customRules);
  return {
    ...configBase,
    theme,
    themeRuleCount: themeRules(theme ?? {}).length,
    resolutionStatus: theme ? "vscode-theme" : "fallback"
  };
}

function syntaxHighlightThemePath(): string | undefined {
  const configuredPath = vscode.workspace.getConfiguration("optitrust").get<string>("syntaxHighlightThemePath", "").trim();
  if (!configuredPath) {
    return undefined;
  }
  if (path.isAbsolute(configuredPath)) {
    return configuredPath;
  }
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  return workspaceRoot ? path.resolve(workspaceRoot, configuredPath) : path.resolve(configuredPath);
}

async function activeThemeJson(activeTheme: string, themePath: string, customRules: readonly TextMateRule[]): Promise<ThemeJson | undefined> {
  try {
    const theme = await loadThemeJson(themePath);
    const tokenColors = [...themeRules(theme), ...customRules];
    return {
      ...theme,
      name: "optitrust-active-vscode-theme",
      tokenColors
    };
  } catch (error) {
    console.warn(`OptiTrust: failed to load VS Code theme ${activeTheme}: ${error instanceof Error ? error.message : String(error)}`);
    return undefined;
  }
}

interface ThemeResolution {
  readonly path: string;
  readonly extensionId: string;
  readonly label?: string;
}

function findTheme(activeTheme: string): ThemeResolution | undefined {
  const names = themeLookupNames(activeTheme);
  for (const extension of vscode.extensions.all) {
    const themes = extension.packageJSON?.contributes?.themes;
    if (!Array.isArray(themes)) {
      continue;
    }
    for (const theme of themes) {
      if (typeof theme.path === "string" && themeMatches(theme, names)) {
        return {
          path: path.join(extension.extensionPath, theme.path),
          extensionId: extension.id,
          label: themeLabel(theme)
        };
      }
    }
  }
  return undefined;
}

function builtinShikiTheme(activeTheme: string): "dark-plus" | "light-plus" | undefined {
  switch (normalizeThemeName(activeTheme)) {
    case "dark 2026":
    case "default dark modern":
    case "dark modern":
    case "default dark+":
    case "default dark plus":
    case "dark+":
    case "dark plus":
    case "visual studio dark":
      return "dark-plus";
    case "light 2026":
    case "default light modern":
    case "light modern":
    case "default light+":
    case "default light plus":
    case "light+":
    case "light plus":
    case "visual studio light":
      return "light-plus";
    default:
      return undefined;
  }
}

function themeLabel(theme: unknown): string | undefined {
  if (!isRecord(theme)) {
    return undefined;
  }
  for (const value of [theme.label, theme.name, theme.id]) {
    if (typeof value === "string") {
      return value;
    }
  }
  return undefined;
}

function themeLookupNames(activeTheme: string): Set<string> {
  const names = new Set<string>();
  const normalized = normalizeThemeName(activeTheme);
  if (normalized) {
    names.add(normalized);
    names.add(normalized.replace(/^default /u, ""));
  }

  const aliases: Record<string, readonly string[]> = {
    "default dark modern": ["dark modern"],
    "default light modern": ["light modern"],
    "default dark+": ["dark+"],
    "default light+": ["light+"],
    "default dark plus": ["dark+"],
    "default light plus": ["light+"],
    "dark+": ["dark plus"],
    "light+": ["light plus"]
  };
  for (const alias of aliases[normalized] ?? []) {
    names.add(alias);
  }
  return names;
}

function themeMatches(theme: unknown, names: ReadonlySet<string>): boolean {
  if (!isRecord(theme)) {
    return false;
  }
  return [
    theme.id,
    theme.label,
    theme.name
  ].some(value => typeof value === "string" && names.has(normalizeThemeName(value)));
}

function normalizeThemeName(name: string): string {
  return name
    .trim()
    .replace(/^%|%$/gu, "")
    .replace(/color theme label$/iu, "")
    .replace(/theme label$/iu, "")
    .replace(/([a-z])([A-Z])/gu, "$1 $2")
    .replace(/\s+/gu, " ")
    .toLowerCase();
}

async function loadThemeJson(themePath: string, seen: Set<string> = new Set()): Promise<ThemeJson> {
  const resolved = path.resolve(themePath);
  if (seen.has(resolved)) {
    return {};
  }
  seen.add(resolved);

  const theme = parseJsonWithComments<ThemeJson>(await fs.readFile(resolved, "utf8"));
  const inherited = theme.include ? await loadThemeJson(path.resolve(path.dirname(resolved), theme.include), seen) : {};
  return {
    ...inherited,
    ...theme,
    colors: {
      ...(inherited.colors ?? {}),
      ...(theme.colors ?? {})
    },
    tokenColors: [
      ...themeRules(inherited),
      ...themeRules(theme)
    ]
  };
}

function customTokenRules(activeTheme: string): TextMateRule[] {
  const customizations = vscode.workspace.getConfiguration("editor").get<Record<string, unknown>>("tokenColorCustomizations", {});
  const rules: TextMateRule[] = [];
  rules.push(...textMateRulesFrom(customizations.textMateRules));

  const themeSpecific = customizations[`[${activeTheme}]`];
  if (isRecord(themeSpecific)) {
    rules.push(...textMateRulesFrom(themeSpecific.textMateRules));
  }
  return rules;
}

function themeRules(theme: ThemeJson): TextMateRule[] {
  return [
    ...textMateRulesFrom(theme.settings),
    ...textMateRulesFrom(theme.tokenColors)
  ];
}

function textMateRulesFrom(value: unknown): TextMateRule[] {
  return Array.isArray(value) ? value.filter(isTextMateRule) : [];
}

function isTextMateRule(value: unknown): value is TextMateRule {
  return isRecord(value) && isRecord(value.settings);
}

function parseJsonWithComments<T>(text: string): T {
  return JSON.parse(stripJsonComments(text)) as T;
}

function stripJsonComments(text: string): string {
  return text
    .replace(/\/\*[\s\S]*?\*\//gu, "")
    .replace(/(^|[^:])\/\/.*$/gmu, "$1");
}

function escapeScriptJson(value: string): string {
  return value.replace(/[<\u2028\u2029]/gu, character => {
    if (character === "<") {
      return "\\u003c";
    }
    if (character === "\u2028") {
      return "\\u2028";
    }
    return "\\u2029";
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/**
 * The diff renderer occasionally fails to initialize under webview security or
 * asset-loading constraints. Showing the raw diff is preferable to an empty
 * panel because the OptiTrust command itself has already succeeded.
 */
function injectDiffFallback(html: string): string {
  if (!html.includes('id="diffDiv"')) {
    return html;
  }

  const fallbackScript = `
<script>
function getOptitrustRawDiffString() {
  if (typeof diffString === 'string') {
    return diffString;
  }
  if (typeof diffStrings === 'object' && diffStrings !== null) {
    var selected = typeof selectedDiffRepresentation === 'string' ? selectedDiffRepresentation : 'cpp';
    return diffStrings[selected] || diffStrings.cpp || diffStrings.surface || diffStrings.internal || diffStrings.typed || '';
  }
  return '';
}

function renderOptitrustRawDiffFallback() {
  var target = document.getElementById('diffDiv');
  var rawDiff = getOptitrustRawDiffString();
  if (!target || target.textContent.trim() !== '' || rawDiff === '') {
    return;
  }
  var warning = document.createElement('p');
  warning.textContent = 'OptiTrust rendered the raw diff because the interactive diff viewer did not load inside VS Code.';
  warning.style.fontFamily = 'sans-serif';
  warning.style.color = '#a15c00';
  var pre = document.createElement('pre');
  pre.textContent = rawDiff;
  pre.style.whiteSpace = 'pre-wrap';
  pre.style.fontFamily = 'var(--vscode-editor-font-family, monospace)';
  pre.style.fontSize = 'var(--vscode-editor-font-size, 13px)';
  pre.style.background = 'var(--vscode-editor-background, #fff)';
  pre.style.color = 'var(--vscode-editor-foreground, #24292f)';
  pre.style.padding = '12px';
  pre.style.overflow = 'auto';
  target.appendChild(warning);
  target.appendChild(pre);
}

window.addEventListener('error', function () {
  window.setTimeout(renderOptitrustRawDiffFallback, 0);
});
document.addEventListener('DOMContentLoaded', function () {
  window.setTimeout(function () {
    renderOptitrustRawDiffFallback();
  }, 800);
});
</script>`;

  if (html.includes("</body>")) {
    return html.replace("</body>", `${fallbackScript}\n</body>`);
  }
  return `${html}\n${fallbackScript}`;
}

function injectDetachButton(html: string, detached: boolean): string {
  if (html.includes('id="optitrustDetachViewButton"')) {
    return html;
  }

  const disabled = detached ? " disabled" : "";
  const label = detached ? "Detached" : "Detach";
  const title = detached ? "This OptiTrust view is detached" : "Detach this OptiTrust view";
  const detachHtml = `
<style>
#optitrustDetachViewButton {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 24px;
  margin-left: auto;
  padding: 2px 8px;
  border: 1px solid var(--vscode-button-border, transparent);
  border-radius: 3px;
  color: var(--vscode-button-secondaryForeground, var(--vscode-foreground, #222222));
  background: transparent;
  font: 12px var(--vscode-font-family, sans-serif);
  cursor: pointer;
}

#optitrustDetachViewButton:hover {
  background: var(--vscode-toolbar-hoverBackground, var(--vscode-list-hoverBackground, rgba(127, 127, 127, 0.14)));
}

#optitrustDetachViewButton:focus-visible {
  outline: 1px solid var(--vscode-focusBorder, #007fd4);
  outline-offset: 1px;
}

#optitrustDetachViewButton:disabled {
  opacity: 0.7;
  cursor: default;
}

#optitrustDetachViewButton:disabled:hover {
  background: transparent;
}
</style>
<button id="optitrustDetachViewButton" type="button" title="${title}"${disabled}>${label}</button>
<script>
(function () {
  window.optitrustVsCodeApi = window.optitrustVsCodeApi || (typeof acquireVsCodeApi === 'function' ? acquireVsCodeApi() : undefined);
  if (!window.optitrustVsCodeApi) {
    return;
  }
  var vscode = window.optitrustVsCodeApi;
  function registerDetachButton() {
    var button = document.getElementById('optitrustDetachViewButton');
    if (!button) {
      return;
    }
    var host = document.getElementById('astControls') || document.getElementById('diffDetachSlot') || document.querySelector('.trace-titlebar');
    if (host && button.parentElement !== host) {
      host.appendChild(button);
    }
    button.addEventListener('click', function () {
      button.textContent = 'Detached';
      button.title = 'This OptiTrust view is detached';
      button.disabled = true;
      vscode.postMessage({ type: 'optitrust.detachView' });
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', registerDetachButton);
  } else {
    registerDetachButton();
  }
}());
</script>`;

  if (html.includes("</body>")) {
    return html.replace("</body>", `${detachHtml}\n</body>`);
  }
  return `${html}\n${detachHtml}`;
}

export async function openHtmlView(
  root: string,
  htmlFile: string,
  viewKind: string,
  metadata: string,
  title: string,
  options: OpenHtmlViewOptions = {}
): Promise<void> {
  let key = options.useLiveView ? LIVE_VIEW_KEY : webviewKey(htmlFile, viewKind, metadata);
  const existing = panels.get(key);
  const state: PanelRuntimeState = {
    root,
    htmlFile,
    includeDetachButton: options.useLiveView,
    lazyDiff: options.lazyDiff,
    initialDiffRepresentation: options.initialDiffRepresentation,
    detached: false
  };
  panelStates.set(key, state);
  if (existing) {
    existing.title = title;
    if (!options.useLiveView) {
      existing.reveal(existing.viewColumn, true);
    }
    existing.webview.html = await htmlWithBase(existing.webview, root, htmlFile, {
      includeDetachButton: options.useLiveView,
      initialDiffRepresentation: state.initialDiffRepresentation,
      detached: state.detached
    });
    return;
  }

  const viewColumn = options.useLiveView ? await prepareAttachedLiveView("html") : vscode.ViewColumn.Beside;
  const panel = vscode.window.createWebviewPanel(OPTITRUST_WEBVIEW_TYPE, title, viewColumn, {
    enableScripts: true,
    retainContextWhenHidden: true,
    localResourceRoots: [vscode.Uri.file(root), vscode.Uri.file(path.dirname(htmlFile))]
  });

  const liveView = options.useLiveView
    ? {
        kind: "html" as const,
        viewColumn,
        getViewColumn: () => panel.viewColumn,
        detach: () => {
          const detachedKey = webviewKey(htmlFile, viewKind, `${metadata}:detached:${Date.now()}`);
          const currentState = panelStates.get(key);
          panels.delete(key);
          panelStates.delete(key);
          key = detachedKey;
          if (currentState) {
            currentState.detached = true;
            panelStates.set(key, currentState);
          }
          panels.set(key, panel);
        },
        dispose: () => panel.dispose()
      }
    : undefined;

  const messageSubscription = panel.webview.onDidReceiveMessage(async (message: unknown) => {
    if (!isRecord(message)) {
      return;
    }
    if (message.type === "optitrust.detachView") {
      if (liveView && isAttachedLiveView(liveView) && detachLiveView()) {
        vscode.window.showInformationMessage("OptiTrust view detached. The next view command will open a new live view.");
      } else {
        vscode.window.showInformationMessage("This OptiTrust view is already detached.");
      }
      return;
    }
    if (message.type === "optitrust.generateDiffRepresentation") {
      const representation = typeof message.representation === "string" ? message.representation : "";
      const currentState = panelStates.get(key);
      const lazyDiff = currentState?.lazyDiff;
      if (!lazyDiff) {
        const warning = "This OptiTrust diff cannot generate another syntax. Re-run View Step Diff.";
        void panel.webview.postMessage({ type: "optitrust.diffGenerationFailed", representation, message: warning });
        vscode.window.showWarningMessage(warning);
        return;
      }
      const viewMode = VIEW_MODES.find(mode =>
        representation === "cpp" ? mode.id === "cpp" : mode.optilambdaRepresentation === representation
      );
      if (!viewMode) {
        const warning = `Unknown OptiTrust diff syntax: ${representation}`;
        void panel.webview.postMessage({ type: "optitrust.diffGenerationFailed", representation, message: warning });
        vscode.window.showWarningMessage(warning);
        return;
      }
      try {
        await runCommand({
          cwd: currentState.root,
          command: path.join(currentState.root, "tools", "view_result.sh"),
          args: [
            "step_diff",
            lazyDiff.relativePath,
            String(lazyDiff.line),
            ...backendFlagsForViewMode(viewMode)
          ],
          title: `OptiTrust: Generate ${viewMode.label} Diff`,
          env: {
            OPTITRUST_NO_BROWSER: "1"
          }
        });
      } catch {
        const warning = `Failed to generate ${viewMode.label} diff.`;
        appendLine(warning);
        void panel.webview.postMessage({ type: "optitrust.diffGenerationFailed", representation, message: warning });
        return;
      }
      currentState.initialDiffRepresentation = representation;
      panel.webview.html = await htmlWithBase(panel.webview, currentState.root, currentState.htmlFile, {
        includeDetachButton: currentState.includeDetachButton,
        initialDiffRepresentation: currentState.initialDiffRepresentation,
        detached: currentState.detached
      });
    }
  });

  panel.onDidDispose(() => {
    messageSubscription.dispose();
    panels.delete(key);
    panelStates.delete(key);
    if (liveView) {
      clearLiveView(liveView);
    }
  });
  panel.onDidChangeViewState(event => {
    if (event.webviewPanel.active) {
      setActiveLiveViewContext(liveView ? isAttachedLiveView(liveView) : false);
    }
  });
  panel.webview.html = await htmlWithBase(panel.webview, root, htmlFile, {
    includeDetachButton: options.useLiveView,
    initialDiffRepresentation: state.initialDiffRepresentation,
    detached: state.detached
  });
  panels.set(key, panel);
  if (liveView) {
    attachLiveView(liveView);
  }
}

export async function openFileOrHtml(root: string, filePath: string, title?: string): Promise<void> {
  if (path.extname(filePath) === ".html") {
    await openHtmlView(root, filePath, "associated", path.basename(filePath), title ?? path.basename(filePath));
    return;
  }

  const document = await vscode.workspace.openTextDocument(vscode.Uri.file(filePath));
  await vscode.window.showTextDocument(document, vscode.ViewColumn.Beside);
}
