#!/usr/bin/env bash
#
# This script is for opening a diff between '${FILEBASE}_before.${FILEEXT}'
# and '${FILEBASE}_after.${FILEEXT}' in a browser. Used by task 'View diff'.
#
# Usage: (This script must be executed with a `pwd` matching the folder that contains the script)
#   ./tools/open_diff.sh ${FILEBASE} ${FILEEXT}
# where ${FILEBASE} is the script name without extension, e.g., label_add.

# LATER: the diff file could be generated by [lib/framework/trace.ml], better than in bash

#==========================================================================
# Processing script arguments

# Setting to ensure that the execution is interrupted in case of error
# FIXME: to do this we'd need to change the computation of sDiffcode
# set -euo pipefail

# TOOLS_FOLDER_RELATIVE denotes the path to the tools folder relative to the current script
TOOLS_FOLDER=$(dirname -- "$( readlink -f -- "$0"; )")
TOOLS_FOLDER_RELATIVE=$(realpath --relative-to=. ${TOOLS_FOLDER})
OPTITRUST_FOLDER="${TOOLS_FOLDER}/.."

# WEB_VIEW_FOLDER denotes the path to the web_view folder relative to the script folder
WEB_VIEW_FOLDER="${TOOLS_FOLDER_RELATIVE}/web_view"

# Parsing arguments
FILEBASE=$1
FILEEXT=$2

# Parameter for diffs
CONTEXTSIZE="10"

# Option for skipping this script
${NODIFFDISPLAY:=""}


#==========================================================================
# Read additional settings

# Read options from the local optitrust_flags.sh or the one at the OptiTrust root
# Example options: CONTEXTSIZE="100", NODIFFDISPLAY="1"
if [ -f "optitrust_flags.sh" ]; then
  source optitrust_flags.sh
fi

if [ -f "${OPTITRUST_FOLDER}/optitrust_flags.sh" ]; then
  source ${OPTITRUST_FOLDER}/optitrust_flags.sh
fi


# If NODIFFDISPLAY=1, interrupt the script
if [ "${NODIFFDISPLAY}" = "1" ]; then
  echo "NODIFFDISPLAY = 1, skipping diff display"
  exit 0;
fi

#==========================================================================
# Generate output file

FILENAME="${FILEBASE}_diff.html"

TITLESTR="${FILEBASE} - OptiTrust Diff"

# Compute a diff in base64 encoding, or return an empty payload when the
# requested representation was not generated.
compute_diff_payload() {
  local BEFORE_FILE=$1
  local AFTER_FILE=$2
  if [ -f "${BEFORE_FILE}" ] && [ -f "${AFTER_FILE}" ]; then
    git diff --ignore-all-space --no-index -U${CONTEXTSIZE} "${BEFORE_FILE}" "${AFTER_FILE}" | base64 -w 0
  else
    printf ""
  fi
}

DIFFCODE=`compute_diff_payload ${FILEBASE}_before.${FILEEXT} ${FILEBASE}_after.${FILEEXT}`

if [ -f "${FILEBASE}_before_surface.opti" ] && [ -f "${FILEBASE}_after_surface.opti" ]; then
  DIFFCODE_OPTILAMBDA_SURFACE=`compute_diff_payload ${FILEBASE}_before_surface.opti ${FILEBASE}_after_surface.opti`
else
  DIFFCODE_OPTILAMBDA_SURFACE=`compute_diff_payload ${FILEBASE}_before.opti ${FILEBASE}_after.opti`
fi
DIFFCODE_OPTILAMBDA_INTERNAL=`compute_diff_payload ${FILEBASE}_before_internal.opti ${FILEBASE}_after_internal.opti`
DIFFCODE_OPTILAMBDA_TYPED=`compute_diff_payload ${FILEBASE}_before_typed.opti ${FILEBASE}_after_typed.opti`

# Don't launch a browser if every available representation has an empty diff.
if [ "$DIFFCODE" == "" ] && [ "$DIFFCODE_OPTILAMBDA_SURFACE" == "" ] && [ "$DIFFCODE_OPTILAMBDA_INTERNAL" == "" ] && [ "$DIFFCODE_OPTILAMBDA_TYPED" == "" ]; then
  echo ">>>============EMPTY DIFF============<<<"
  exit 0
fi

# Generate the JavaScript definitions
DIFFSTR="var diffStrings = { cpp: window.atob(\"${DIFFCODE}\"), surface: window.atob(\"${DIFFCODE_OPTILAMBDA_SURFACE}\"), internal: window.atob(\"${DIFFCODE_OPTILAMBDA_INTERNAL}\"), typed: window.atob(\"${DIFFCODE_OPTILAMBDA_TYPED}\") };"

# Take templace and substitute ${WEB_VIEW_FOLDER}, ${INSERT_TITLE}, and ${INSERT_DIFF}
TEMPLATE="${WEB_VIEW_FOLDER}/diff_template.html"
cp ${TEMPLATE} ${FILENAME}
sed -i "s#{INSERT_TITLE}#${TITLESTR}#g;s#{WEB_VIEW_FOLDER}#${WEB_VIEW_FOLDER}#g;s#{INSERT_DIFF}#${DIFFSTR}#g" ${FILENAME}
# Note: there seems to be an issue if performing the sed one after the other, so keep them grouped

echo "Generated ${FILENAME}"

#==========================================================================
# Open output file

CURPATH=`pwd`
TARGET=$(realpath --relative-to=${OPTITRUST_FOLDER} ${FILENAME})

# Open the browser with the target file
echo "Opening browser on file://${CURPATH}/${TARGET}"
${TOOLS_FOLDER}/open_in_browser.sh ${TARGET} "${TITLESTR}"
