#!/bin/bash

# Usage:
#   ./tools/view_result.sh ${FILEBASE} ${FILEEXT} ${MODE}
#
# where MODE is one of:
# - view_diff: to view the diff at the targeted line
# - view_diff_enc: likewise, but disable the encoding

# FIXME: the diff file should be generated by [trace.ml], shouldn't do that in bash

#==========================================================================
# Processing script arguments

# Setting to ensure that the execution is interrupted in case of error
# FIXME: to do this we'd need to change the computation of sDiffcode
# set -euo pipefail


# Path to the tools and optitrust folder
TOOLS_FOLDER=$(dirname -- "$( readlink -f -- "$0"; )")
OPTITRUST_FOLDER="${TOOLS_FOLDER}/.."
WEB_VIEW_FOLDER="${TOOLS_FOLDER}/web_view"

# Parsing arguments
FILEBASE=$1
FILEEXT=$2
MODE=$3

# Parameter for diffs
CONTEXTSIZE="10"

# Option for skipping this script
${NODIFFDISPLAY:=""}


#==========================================================================
# Read additional settings


# Read options from the local optitrust_flags.sh or the one at the OptiTrust root
# Example options: CONTEXTSIZE="100", NODIFFDISPLAY="1"
if [ -f "optitrust_flags.sh" ]; then
  source optitrust_flags.sh
fi

if [ -f "${OPTITRUST_FOLDER}/optitrust_flags.sh" ]; then
  source ${OPTITRUST_FOLDER}/optitrust_flags.sh
fi


# If NODIFFDISPLAY=1, interrupt the script
if [ "${NODIFFDISPLAY}" = "1" ]; then
  echo "NODIFFDISPLAY = 1, skipping diff display"
  exit 0;
fi

#==========================================================================
# Generate output file

TARGET="${FILEBASE}_diff.html"

TITLESTR="${FILEBASE} - OptiTrust Diff"


# Treat the MODE="view_diff_enc"
ENCOPT=""
if [ "${MODE}" = "view_diff_enc" ]; then
  ENCOPT="_enc"
fi

# Compute the diff in base64 encoding
DIFFCODE=`git diff --ignore-all-space --no-index -U${CONTEXTSIZE} ${FILEBASE}_before${ENCOPT}.${FILEEXT} ${FILEBASE}_after${ENCOPT}.${FILEEXT} | base64 -w 0`

# Don't launch a browser for an empty diff
if [ "$DIFFCODE" == "" ]; then
  echo ">>>============EMPTY DIFF============<<<"
  exit 0
fi

# Generate the JavaScript definition
DIFFSTR="var diffString = window.atob(\"${DIFFCODE}\");"

# Take templace and substitute ${WEB_VIEW_FOLDER}, ${INSERT_TITLE}, and ${INSERT_DIFF}
TEMPLATE="${WEB_VIEW_FOLDER}/diff_template.html"
cp ${TEMPLATE} ${TARGET}
sed -i "s#{INSERT_TITLE}#${TITLESTR}#g;s#{WEB_VIEW_FOLDER}#${WEB_VIEW_FOLDER}#g;s#{INSERT_DIFF}#${DIFFSTR}#g" ${TARGET}
# Note: there seems to be an issue if performing the sed one after the other, so keep them grouped

# echo "Generated ${TARGET}"

#==========================================================================
# Open output file

# Open the browser with the target file
${TOOLS_FOLDER}/open_in_browser.sh ${TARGET} "${TITLESTR}"
