#!/usr/bin/env bash
#
# This script is for opening a diff between '${FILEBASE}_before.${FILEEXT}'
# and '${FILEBASE}_after.${FILEEXT}' in a browser. Used by task 'View diff'.
#
# Usage: (This script must be executed with a `pwd` matching the folder that contains the script)
#   ./tools/open_diff.sh ${FILEBASE} ${FILEEXT}
# where ${FILEBASE} is the script name without extension, e.g., label_add.

# LATER: the diff file could be generated by [lib/framework/trace.ml], better than in bash

#==========================================================================
# Processing script arguments

# Setting to ensure that the execution is interrupted in case of error
# FIXME: to do this we'd need to change the computation of sDiffcode
# set -euo pipefail

# TOOLS_FOLDER_RELATIVE denotes the path to the tools folder relative to the current script
TOOLS_FOLDER=$(dirname -- "$( readlink -f -- "$0"; )")
TOOLS_FOLDER_RELATIVE=$(realpath --relative-to=. ${TOOLS_FOLDER})
OPTITRUST_FOLDER="${TOOLS_FOLDER}/.."

# WEB_VIEW_FOLDER denotes the path to the web_view folder relative to the script folder
WEB_VIEW_FOLDER="${TOOLS_FOLDER_RELATIVE}/web_view"

# Parsing arguments
FILEBASE=$1
FILEEXT=$2

# Parameter for diffs
CONTEXTSIZE="10"

# Option for skipping this script
${NODIFFDISPLAY:=""}


#==========================================================================
# Read additional settings

# Read options from the local optitrust_flags.sh or the one at the OptiTrust root
# Example options: CONTEXTSIZE="100", NODIFFDISPLAY="1"
if [ -f "optitrust_flags.sh" ]; then
  source optitrust_flags.sh
fi

if [ -f "${OPTITRUST_FOLDER}/optitrust_flags.sh" ]; then
  source ${OPTITRUST_FOLDER}/optitrust_flags.sh
fi


# If NODIFFDISPLAY=1, interrupt the script
if [ "${NODIFFDISPLAY}" = "1" ]; then
  echo "NODIFFDISPLAY = 1, skipping diff display"
  exit 0;
fi

#==========================================================================
# Generate output file

FILENAME="${FILEBASE}_diff.html"

TITLESTR="${FILEBASE} - OptiTrust Diff"

# Compute the diff in base64 encoding
DIFFCODE=`git diff --ignore-all-space --no-index -U${CONTEXTSIZE} ${FILEBASE}_before.${FILEEXT} ${FILEBASE}_after.${FILEEXT} | base64 -w 0`

# Don't launch a browser for an empty diff
if [ "$DIFFCODE" == "" ]; then
  echo ">>>============EMPTY DIFF============<<<"
  exit 0
fi

# Generate the JavaScript definition
DIFFSTR="var diffString = window.atob(\"${DIFFCODE}\");"

# Take templace and substitute ${WEB_VIEW_FOLDER}, ${INSERT_TITLE}, and ${INSERT_DIFF}
TEMPLATE="${WEB_VIEW_FOLDER}/diff_template.html"
cp ${TEMPLATE} ${FILENAME}
sed -i "s#{INSERT_TITLE}#${TITLESTR}#g;s#{WEB_VIEW_FOLDER}#${WEB_VIEW_FOLDER}#g;s#{INSERT_DIFF}#${DIFFSTR}#g" ${FILENAME}
# Note: there seems to be an issue if performing the sed one after the other, so keep them grouped

echo "Generated ${FILENAME}"

#==========================================================================
# Open output file

CURPATH=`pwd`
TARGET=$(realpath --relative-to=${OPTITRUST_FOLDER} ${FILENAME})

# Open the browser with the target file
echo "Opening browser on file://${CURPATH}/${TARGET}"
${TOOLS_FOLDER}/open_in_browser.sh ${TARGET} "${TITLESTR}"
